### ISSUE TITLE
Add ability to check if a type/instance/interface is already registered or can be resolved

### ISSUE THREAD

**Issue by icnocop** [gasparnagy/BoDi#3]
I'd like to request the ability to check if a type/instance/interface is registered or can be resolved.

As a work-around, I have to wrap a call to `Resolve` in a `try...catch (BoDi.ObjectContainerException)`.

In my scenario, I have two test projects, each have a `[Before]` SpecFlow binding and register a different instance of an object of the same interface. For example, test project B references test project A and the test assembly generated by test project A is configured as an external step assembly in test project B's configuration file's `stepAssemblies`. When running a scenario in test project B, test project B's `[Before]` hook is run first and instance X is registered without issues. However, soon after that, test project A's `[Before]` hook is run and overwrites the registered instance with its own instance Y. This causes an issue in the steps in test project B which expect the instance of that type to contain specific property values, etc.

So I'm thinking we may want to have an `IsRegistered` and/or `TryResolve` method.

Other options I've explored but don't seem to be practical solutions:
1. Pass the object in the `[Before]` method hook (i.e. dependency injection on the method).
    Currently throws an exception: `System.Reflection.TargetParameterCountException: Parameter count mismatch.`
2. Pass the object in the constructor of the `[Binding]` class.
   If the object is not registered, currently throws an exception: `BoDi.ObjectContainerException: Interface cannot be resolved: IMyInterface`

In both options, if the instance is null then it would indicate that the type/instance/interface could not be resolved.

Thank you.

**Comment by darrencauthon** [comment]
Just a thought... it's generally a red flag to have to check a container for a registration.  I think I understand your situation, and I think it's caused by the test setup.  The "before" steps should be run in relative isolation, where they don't touch each other.  So, if a class is registered in some way in one "before," it wouldn't be registered by any other "before" steps.  

Plus, all of the "before" steps would have very basic setup, setup that it necessary only to fire a test up.  Any test-specific setup would be in the Gherkin, which would contain the test-specific code.  So there'd be no way for the setup of one step to overwrite the setup of another step, because only the steps relevant to the specific test would be run.

This pull request introduces a minor change, and I think I'd vote to include it... but part of me wants to vote to reject it because it's only making the tool easier to abuse.

**Comment by darrencauthon** [comment]
Not that this project takes votes 🗳  :smile:

**Comment by ramiabughazaleh** [comment]
FWIW all the dependency containers I've used already have this type of functionality.

`IUnityContainer` has an [`IsRegistered` method](https://msdn.microsoft.com/en-us/library/ff661604(v=pandp.51).aspx).

Castle Windsor has a [`HasComponent` method](https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/MicroKernel/IKernel.cs#L180).

Autofac has a [`TryGetRegistration` method](https://github.com/autofac/Autofac/blob/d44e09d37863e13aa09eefa6f249caf1e5caf0f1/src/Autofac/Core/IComponentRegistry.cs#L51) and an [`IsRegistered` method](https://github.com/autofac/Autofac/blob/d44e09d37863e13aa09eefa6f249caf1e5caf0f1/src/Autofac/Core/IComponentRegistry.cs#L58).

Ninject has a [`GetBindings` method](https://github.com/ninject/Ninject/blob/005e6f9e38414a38ae7c6aaf346c74ec64212609/src/Ninject/IReadOnlyKernel.cs#L43).

I'm not exactly sure how this type of functionality could be considered "abuse" since the `RegisterInstanceAs` method can just otherwise be encapsulated within a `try...catch` to get the same behavior.

I would rather not have to explicitly decorate the Gherkin files with each common dependency as that seems like it creates unnecessary complexity which may not otherwise be relevant to the behaviors being tested in the feature file itself.
Instead, I want to have the flexibility to implement a "first registration wins" type of behavior without BoDi throwing exceptions which need to be caught for example.

I ran into this issue again when trying to register a generic `Logger` type that was already registered in a different step assembly. I'm not sure if decorating each feature file with `@Logger` is the best approach here for example.

Thank you.
🗳 😄
